services:
  miku-bot:
    image: 007hikari/miku-bot:latest
    container_name: miku-bot
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - .env
    environment:
      SUPERUSERS: '[]'
      COMMAND_START: '["/"]'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/history_book:/app/data/history_book
      - ./data/resources:/app/src/common/resources
      - ./data/configs:/app/configs

      #! 命名卷，与其他容器共享卷
      # - ./data/bilinote_shared:/app/data/local_bilinote
      # - ./data/trend_news:/app/data/news
      # - /home/kami/secrets/data/stock:/app/data/stock
      - vol_shared_stock_data:/app/data/stock/data:ro                 # 与Daily stock analysis共享股票数据
      - vol_shared_stock_reports:/app/data/stock/reports:ro
      - vol_shared_bilinote:/app/data/local_bilinote:ro               # 与Bilinote共享笔记数据
      - vol_shared_trendradar:/app/data/news:ro                       # 与TrendRadar共享新闻数据
      - ./data/chat_history:/app/data/chat_history                    # ChatRecorder 数据库 (SQLite)
      - ./data/memory_store:/app/data/memory_store                    # ChromaDB 向量数据库
    # depends_on:
    #   - napcat
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true

volumes:
  # 笔记数据
  vol_shared_bilinote:
    external: true
  # 新闻数据
  vol_shared_trendradar:
    external: true
  # 股票数据
  vol_shared_stock_data:
    external: true
  vol_shared_stock_reports:
    external: true


