version: "3"

x-config-host: &config-host ${HOST:-0.0.0.0}
x-config-port: &config-port ${PORT:-9999}

services:
  nonebot:
    build: .
    ports:
      - *config-port
    env_file:
      - .env.prod
    environment:
      ENVIRONMENT: prod
      HOST: *config-host
      PORT: *config-port
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/bilinote_shared:/app/data/local_bilinote
      - /home/kami/secrets/data/trend_news:/app/data/news